<?php
function handle_update($u){
global $TXT,$BTN;
if(isset($u['callback_query'])){handle_cb($u['callback_query']);return;}
if(isset($u['message'])){handle_msg($u['message']);return;}
}
function is_valid_act_pass($p){
if(preg_match('/[\x{0600}-\x{06FF}]/u',$p))return false;
if(preg_match('/\s/',$p))return false;
return (bool)preg_match('/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z0-9!@#$%^&*()\-\_=+\[\]{};:,.?<>\/\\\\|~`]{4,64}$/',$p);
}
function start_plan_now($cid,$chat,$uid_hint){
global $TXT,$BTN;
$st=load_state($cid);
if($st&&($st['phase']??'')!=='done'){return;}
$st=['phase'=>'rules','kyc'=>[],'acks'=>[],'kyc_on'=>false,'misc_on'=>false,'fb_change'=>null,'token'=>bin2hex(random_bytes(4)),'link_tokens'=>null,'link_tokens_used'=>['buyer'=>null,'seller'=>null],'group_username'=>($chat['username']??'')];
save_state($cid,$st);
api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['rules_title'],'parse_mode'=>'HTML','reply_markup'=>json_encode(rules_kb($st,$uid_hint,false),JSON_UNESCAPED_UNICODE)]);
}
function autoplan_on_join($cid,$chat,$members){
$apf=data_dir().'/ap_'.$cid.'.json';
$rec=@json_decode(@file_get_contents($apf),true);
if(!is_array($rec)){$rec=['first'=>0,'count'=>0,'scheduled'=>false];}
$now=time();
$cnt=is_array($members)?count($members):0;
$ok=false;
if($cnt>=2){$ok=true;}else{
if(($rec['first']??0)>0&&($now-($rec['first']??0))<=1800){$rec['count']=intval($rec['count']??0)+1;$ok=$rec['count']>=2;}else{$rec=['first'=>$now,'count'=>1,'scheduled'=>false];}
}
if($ok&&!($rec['scheduled']??false)){
$rec['scheduled']=true;
@file_put_contents($apf,json_encode($rec,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX);
$st=load_state($cid);
if(!$st||($st['phase']??'')==='done'){sleep(6);start_plan_now($cid,$chat,0);}
@unlink($apf);
}else{
@file_put_contents($apf,json_encode($rec,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX);
}
}
function handle_msg($m){
global $TXT,$BTN;
$from=$m['from']??[];
$uid=$from['id']??0;
$un=$from['username']??'';
$chat=$m['chat']??[];
$cid=$chat['id']??0;
$ctype=$chat['type']??'';
$txt=trim($m['text']??'');
$cmd='';
if($txt&&$txt[0]=='/'){if(preg_match('/^\/([A-Za-z_]+)(?:@[\w_]+)?/u',$txt,$mm)){$cmd=strtolower($mm[1]);}}
if(in_array($ctype,['group','supergroup'])&&isset($m['new_chat_members'])&&is_array($m['new_chat_members'])){autoplan_on_join($cid,$chat,$m['new_chat_members']);}
if($ctype==='private'&&function_exists('channel_enforce_join')){
if(!channel_enforce_join($uid,$cid,['chat_type'=>'private','message_id'=>$m['message_id']??0]))return;
}
if(in_array($ctype,['group','supergroup'])&&$cmd!==''&&function_exists('channel_enforce_join')){
$ctx=['chat_type'=>$ctype,'message_id'=>$m['message_id']??0,'command'=>$cmd,'reply_to'=>$m['message_id']??0];
if(!channel_enforce_join($uid,$cid,$ctx))return;
}
if(in_array($ctype,['group','supergroup'])&&$cmd==='plan'){
$st=load_state($cid);
if($st&&($st['phase']??'')!=='done'){api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['plan_busy'],'parse_mode'=>'HTML']);return;}
start_plan_now($cid,$chat,$uid);
return;
}
if(in_array($ctype,['group','supergroup'])&&$cmd==='clean'){
$lim_ok=true;
$is_admin=admin_is_user($uid);
if(!$is_admin){
$lf=data_dir().'/limit.json';
$all=@json_decode(@file_get_contents($lf),true);if(!is_array($all))$all=[];
$key=(string)$cid;
$w=$all[$key]??['ts'=>[]];
$now=time();
$w['ts']=array_values(array_filter($w['ts'],function($t)use($now){return ($now-$t)<=1800;}));
if(count($w['ts'])>=2){$lim_ok=false;api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['clean_limit'],'parse_mode'=>'HTML']);}else{$w['ts'][]=$now;$all[$key]=$w;@file_put_contents($lf,json_encode($all,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX);}
}
if(!$lim_ok)return;
del_state($cid);
api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['clean_ok'],'parse_mode'=>'HTML']);
if(!$is_admin){sleep(3);start_plan_now($cid,$chat,$uid);}
return;
}
if($ctype==='group'||$ctype==='supergroup'){
$st=load_state($cid);
    if($st&&($st['phase']??'')==='await_receipt'&&((isset($m['photo'])&&is_array($m['photo']))||isset($m['document']))){
    $amt=(int)($st['total']??get_total($st));
    $admin_tag=admin_mentions_text($TXT);
    $msg=($admin_tag!==''?$admin_tag.' ':'').$TXT['receipt_agreed_amount_prefix'].number_format($amt).$TXT['receipt_agreed_amount_suffix']."\n".$TXT['admin_wait_confirm_short'];
$rid=bin2hex(random_bytes(3));
$kb=['inline_keyboard'=>[[['text'=>$BTN['admin_approve'],'callback_data'=>'admin_ok:'.$rid]]]];
$res=api('sendMessage',['chat_id'=>$cid,'text'=>$msg,'parse_mode'=>'HTML','reply_to_message_id'=>$m['message_id'],'allow_sending_without_reply'=>true,'reply_markup'=>json_encode($kb,JSON_UNESCAPED_UNICODE)]);
if(!isset($st['receipts'])||!is_array($st['receipts'])){$st['receipts']=[];}
$st['receipts'][$rid]=['from'=>$uid,'msg_id'=>$res['result']['message_id']??0];
$st['phase']='await_admin_confirm';
save_state($cid,$st);
return;
}
}
if($txt&&strpos($txt,'/start')===0&&$ctype==='private'){
preg_match('/^\/start\s*(.*)$/',$txt,$mm);
$param=trim($mm[1]??'');
$info=parse_start($param);
if(!$info){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['greet'],'parse_mode'=>'HTML']);return;}
if(($info['kind']??'')==='get'){
$found=find_chat_by_token($info['token']);
if(!$found){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['invalid_link'],'parse_mode'=>'HTML']);return;}
$role=$found['role'];
$chat_id=$found['chat_id'];
$st=load_state($chat_id);
if(!$st){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['invalid_link'],'parse_mode'=>'HTML']);return;}
if(!isset($st['link_tokens_used'])||!is_array($st['link_tokens_used'])){$st['link_tokens_used']=['buyer'=>null,'seller'=>null];}
$used_b=$st['link_tokens_used']['buyer'];
$used_s=$st['link_tokens_used']['seller'];
if(($role==='buyer'&&$used_b!==null&&$used_b!=$uid)||($role==='seller'&&$used_s!==null&&$used_s!=$uid)){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['link_used_by_other'],'parse_mode'=>'HTML']);return;}
if(($role==='buyer'&&$used_s!==null&&$used_s==$uid)||($role==='seller'&&$used_b!==null&&$used_b==$uid)){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['link_cannot_use_both'],'parse_mode'=>'HTML']);return;}
if($role==='buyer'){
$st['link_tokens_used']['buyer']=$uid;
$st['buyer_id']=$uid;
$st['buyer_username']=$un??'';
save_state($chat_id,$st);
save_uctx($uid,['chat_id'=>$chat_id,'role'=>'buyer']);
api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['buyer_start'],'parse_mode'=>'HTML']);
return;
}else{
$st['link_tokens_used']['seller']=$uid;
$st['seller_id']=$uid;
$st['seller_username']=$un??'';
save_state($chat_id,$st);
save_uctx($uid,['chat_id'=>$chat_id,'role'=>'seller','need'=>'email']);
api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['seller_start'],'parse_mode'=>'HTML']);
return;
}
}
if(($info['kind']??'')==='role'){
$st=load_state($info['chat_id']);
if(!$st||($st['token']??'')!==$info['token']){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['invalid_link'],'parse_mode'=>'HTML']);return;}
if($info['role']==='buyer'){
if(($st['buyer_id']??0)===0){$st['buyer_id']=$uid;$st['buyer_username']=$un??'';}elseif($st['buyer_id']!=$uid){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['buyer_already'],'parse_mode'=>'HTML']);return;}
save_state($info['chat_id'],$st);
save_uctx($uid,['chat_id'=>$info['chat_id'],'role'=>'buyer']);
api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['buyer_start'],'parse_mode'=>'HTML']);
return;
}else{
if(($st['seller_id']??0)===0){$st['seller_id']=$uid;$st['seller_username']=$un??'';}elseif($st['seller_id']!=$uid){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['seller_already'],'parse_mode'=>'HTML']);return;}
save_state($info['chat_id'],$st);
save_uctx($uid,['chat_id'=>$info['chat_id'],'role'=>'seller','need'=>'email']);
api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['seller_start'],'parse_mode'=>'HTML']);
return;
}
}
api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['invalid_link'],'parse_mode'=>'HTML']);
return;
}
if($ctype==='private'&&$txt){
$ux=load_uctx($uid);
if($ux){
$gid=$ux['chat_id'];
$st=load_state($gid);
if(!$st){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['plan_not_found'],'parse_mode'=>'HTML']);return;}
if(($ux['role']??'')==='buyer'){
if(!preg_match('/^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$/',$txt)){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['send_valid_email_buyer'],'parse_mode'=>'HTML']);return;}
$st['buyer_email']=$txt;
save_state($gid,$st);
api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['buyer_email_ok'],'parse_mode'=>'HTML']);
return;
}
if(($ux['role']??'')==='seller'){
    if(($st['await_code']??false)===true){
    $group_label=$TXT['seller_code_group_label']??'Group:';
    $code_tpl=$TXT['seller_code_template']??'';
    $send=strtr($code_tpl,[
    '{code}'=>htmlspecialchars($txt),
    '{group_id}'=>$gid,
    '{group_label}'=>$group_label,
    ]);
    if(!admin_broadcast('sendMessage',['text'=>$send,'parse_mode'=>'HTML'])){
        api('sendMessage',['chat_id'=>$uid,'text'=>$send,'parse_mode'=>'HTML']);
    }
$st['await_code']=false;
save_state($gid,$st);
api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['code_sent_to_admin'],'parse_mode'=>'HTML']);
return;
}
if(($ux['need']??'email')==='email'){
if(!preg_match('/^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$/',$txt)){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['send_valid_email_seller'],'parse_mode'=>'HTML']);return;}
$st['seller_email']=$txt;
save_state($gid,$st);
save_uctx($uid,['chat_id'=>$gid,'role'=>'seller','need'=>'pass']);
api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['ask_pass'],'parse_mode'=>'HTML']);
return;
}else{
if(!is_valid_act_pass($txt)){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['pass_invalid'],'parse_mode'=>'HTML']);return;}
$st['seller_pass']=$txt;
save_state($gid,$st);
api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['seller_info_ok'],'parse_mode'=>'HTML']);
if(empty($st['notified_admin'])){
$st['notified_admin']=true;
save_state($gid,$st);
$glink='';
if(isset($st['group_username'])&&$st['group_username']!==''){$glink='https://t.me/'.$st['group_username'];}
    $user_link_tpl=$TXT['user_link_template']??'';
    $view_profile=$TXT['admin_profile_view_label']??'';
    $seller_username=$st['seller_username']??'';
    $seller_link_label=$seller_username!==''?'@'.$seller_username:$view_profile;
    $seller_tag=$user_link_tpl!==''?strtr($user_link_tpl,['{user_id}'=>$st['seller_id'],'{label}'=>$seller_link_label]):$seller_link_label;
$adm_text=$TXT['admin_info_title']."\n".$TXT['admin_info_seller'].$seller_tag."\n".$TXT['admin_info_email']."\n".htmlspecialchars($st['seller_email'])."\n".$TXT['admin_info_pass']."\n".htmlspecialchars($st['seller_pass']);
$kb_rows=[[['text'=>$BTN['admin_msg_seller'],'callback_data'=>'msg_seller:'.$gid]],[['text'=>$BTN['admin_msg_buyer'],'callback_data'=>'msg_buyer:'.$gid]],[['text'=>$BTN['seller_wrong'],'callback_data'=>'seller_bad:'.$gid]],[$glink!==''?['text'=>$BTN['admin_group'],'url'=>$glink]:['text'=>$BTN['admin_group'],'callback_data'=>'no_group:'.$gid]]];
    $kb=['inline_keyboard'=>$kb_rows];
    if(!admin_broadcast('sendMessage',['text'=>$adm_text,'parse_mode'=>'HTML','disable_web_page_preview'=>true,'reply_markup'=>json_encode($kb,JSON_UNESCAPED_UNICODE)])){
        api('sendMessage',['chat_id'=>$uid,'text'=>$adm_text,'parse_mode'=>'HTML','disable_web_page_preview'=>true,'reply_markup'=>json_encode($kb,JSON_UNESCAPED_UNICODE)]);
    }
}
return;
}
}
}
}
if($ctype==='private'&&admin_is_user($uid)&&$txt!==''){
if(admin_on_private_text($uid,$txt))return;
}
if($ctype==='private'&&$txt!==''){
$files=list_plan_files();
foreach($files as $f){
$a=@json_decode(@file_get_contents($f),true);
if(!is_array($a))continue;
$br=$a['bridge']??null;
if(is_array($br)&&($br['on']??false)){
$admin_id=(int)($br['admin']??0);
if($uid===($a['buyer_id']??-1)&&$admin_id>0){api('sendMessage',['chat_id'=>$admin_id,'text'=>$TXT['reply_from_buyer_prefix'].$txt,'parse_mode'=>'HTML']);return;}
if($uid===($a['seller_id']??-1)&&$admin_id>0){api('sendMessage',['chat_id'=>$admin_id,'text'=>$TXT['reply_from_seller_prefix'].$txt,'parse_mode'=>'HTML']);return;}
}
}
}
if(in_array($ctype,['group','supergroup'])&&$txt&&!$cmd){
$st=load_state($cid);
if($st&&($st['phase']??'')==='await_price'){
if(!preg_match('/^\d[\d, ]*$/',$txt)){api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['only_number_price'],'parse_mode'=>'HTML']);return;}
$amount=(int)str_replace([',',' '],['',''],$txt);
if($amount<50000){api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['min_price'],'parse_mode'=>'HTML']);return;}
$base=compute_fee($amount);
$extra=((isset($st['fb_change'])&&$st['fb_change']===true)?10000:0);
$misc=((bool)($st['misc_on']??false))?10000:0;
$kycfee=((bool)($st['kyc_on']??false))?5000:0;
$st['amount']=$amount;
$st['fee_base']=$base;
$st['fee_extra_change']=$extra;
$st['fee_misc']=$misc;
$st['kyc_fee']=$kycfee;
$st['fee']=$base+$extra+$misc;
$st['total']=$amount+$base+$extra+$misc+$kycfee;
$st['phase']='invoice';
$st['amt_acks']=[];
save_state($cid,$st);
$msg=api('sendMessage',['chat_id'=>$cid,'text'=>invoice_text($st),'parse_mode'=>'HTML','reply_markup'=>json_encode(invoice_kb($st,$uid,false),JSON_UNESCAPED_UNICODE)]);
api('pinChatMessage',['chat_id'=>$cid,'message_id'=>$msg['result']['message_id']??null,'disable_notification'=>true]);
return;
}
}
}
function handle_cb($cb){
global $TXT,$BTN;
$qid=$cb['id']??'';
$from=$cb['from']??[];
$uid=$from['id']??0;
$un=$from['username']??'';
$msg=$cb['message']??[];
$chat=$msg['chat']??[];
$cid=$chat['id']??0;
$mid=$msg['message_id']??0;
$data=$cb['data']??'';
if(function_exists('channel_handle_callback')&&channel_handle_callback($cb))return;
$ctype=$chat['type']??'';
if(function_exists('channel_enforce_join')&&$cid){
$ctx=['chat_type'=>$ctype,'message_id'=>$mid,'kind'=>'callback','reply_to'=>$mid];
if(!channel_enforce_join($uid,$cid,$ctx)){
if($qid!==''){api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>defined('CHANNEL_FORCE_JOIN_ALERT_TEXT')?CHANNEL_FORCE_JOIN_ALERT_TEXT:'برای استفاده از ربات ابتدا عضو کانال شوید','show_alert'=>true]);}
return;
}
}
if(!$cid){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
$st=load_state($cid);
if(admin_on_callback($data,$uid,$qid,$cid,$mid,$st))return;
if(!$st){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
if(in_array($data,['tgl_act','tgl_fb','tgl_gg','tgl_kyc','tgl_misc','ack_go','lock'])){
if(($st['phase']??'')!=='rules'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
if($data==='lock'){api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['lock_btn']]);return;}
if($data==='tgl_kyc'){$st['kyc_on']=!((bool)($st['kyc_on']??false));save_state($cid,$st);}
if($data==='tgl_misc'){$st['misc_on']=!((bool)($st['misc_on']??false));if(($st['misc_on']??false)===true){$st['kyc']=[];}$st['fb_change']=null;save_state($cid,$st);}
if(in_array($data,['tgl_act','tgl_fb','tgl_gg'])){
if(($st['misc_on']??false)===true){api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['need_method']]);return;}
$map=['tgl_act'=>'act','tgl_fb'=>'fb','tgl_gg'=>'gg'];
$k=$map[$data];
$arr=$st['kyc']??[];
if(in_array($k,$arr)){$arr=array_values(array_diff($arr,[$k]));}else{$arr[]=$k;}
$st['kyc']=$arr;
save_state($cid,$st);
}
if($data==='ack_go'){
if(!isset($st['acks'])){$st['acks']=[];}
$st['acks'][$uid]=true;
save_state($cid,$st);
}
$need_both=(bool)($st['kyc_on']??false);
$ack_count=count($st['acks']??[]);
$acks_ok=$need_both?($ack_count>=2):($ack_count>=1);
$has_method=(($st['misc_on']??false)===true)||(count($st['kyc']??[])>=1);
if($acks_ok&&$has_method){
$ask_fb=(($st['misc_on']??false)!==true)&&need_fb_question($st)&&($st['fb_change']===null);
api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode(rules_kb($st,$uid,true),JSON_UNESCAPED_UNICODE)]);
if($ask_fb){
$st['phase']='fb_change';
save_state($cid,$st);
api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['rules_need_fbq'],'parse_mode'=>'HTML','reply_markup'=>json_encode(fbq_kb(false),JSON_UNESCAPED_UNICODE)]);
api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['req_price_ack']]);
return;
}else{
$st['phase']='await_price';
save_state($cid,$st);
api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['await_price'],'parse_mode'=>'HTML']);
$msgtxt=$need_both?$TXT['both_then_next']:$TXT['ack_done'];
api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$msgtxt]);
return;
}
}else{
$hint=(!$has_method)?$TXT['need_method']:($need_both?(($ack_count==1)?$TXT['wait_second_user']:$TXT['need_both']):$TXT['need_one']);
api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode(rules_kb($st,$uid,false),JSON_UNESCAPED_UNICODE)]);
api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$hint]);
return;
}
}
if(in_array($data,['fbchg_on','fbchg_off'])){
if(($st['phase']??'')!=='fb_change'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
$st['fb_change']=($data==='fbchg_on');
save_state($cid,$st);
api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode(fbq_kb(true),JSON_UNESCAPED_UNICODE)]);
$st['phase']='await_price';
save_state($cid,$st);
api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['await_price'],'parse_mode'=>'HTML']);
api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['ack_done']]);
return;
}
if(in_array($data,['amt_ok','amt_edit'])){
if(($st['phase']??'')!=='invoice'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
if($data==='amt_edit'){
$st['phase']='await_price';
$st['amt_acks']=[];
save_state($cid,$st);
api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['edit_price'],'parse_mode'=>'HTML']);
api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['edited_price_ack']]);
return;
}
if($data==='amt_ok'){
if(!isset($st['amt_acks'])){$st['amt_acks']=[];}
$st['amt_acks'][$uid]=true;
save_state($cid,$st);
api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode(['inline_keyboard'=>[]],JSON_UNESCAPED_UNICODE)]);
$st['phase']='method';
save_state($cid,$st);
api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['method_title'],'parse_mode'=>'HTML','reply_markup'=>json_encode(method_kb(),JSON_UNESCAPED_UNICODE)]);
api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['ack_done']]);
return;
}
}
if($data==='m_auto'){
if(($st['phase']??'')!=='method'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
if(function_exists('admin_flags_is_disabled')&&admin_flags_is_disabled('auto')){api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['method_disabled']]);return;}
$total=(int)($st['total']??get_total($st));
$st['phase']='pay_auto';
$st['total']=$total;
$st['payer_id']=null;
save_state($cid,$st);
$kb=['inline_keyboard'=>[[['text'=>$BTN['build_pay'],'callback_data'=>'build_pay']],[['text'=>$BTN['change_method'],'callback_data'=>'back_method']]]];
    $total_prefix=$TXT['invoice_total_value_prefix']??'';
    $total_suffix=$TXT['invoice_total_value_suffix']??'';
    $total_line=$total_prefix.number_format($total).$total_suffix;
    api('editMessageText',['chat_id'=>$cid,'message_id'=>$mid,'text'=>$TXT['invoice_total_title']."\n".$total_line,'parse_mode'=>'HTML']);
api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode($kb,JSON_UNESCAPED_UNICODE)]);
api('answerCallbackQuery',['callback_query_id'=>$qid]);
return;
}
if($data==='build_pay'){
if(($st['phase']??'')!=='pay_auto'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
$st['payer_id']=$uid;
save_state($cid,$st);
$res=build_zp_link($cid,$st['total'],$uid);
if(!$res['ok']){$err=$res['err']??($TXT['build_pay_error']??'');api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$err]);return;}
$kb=['inline_keyboard'=>[[['text'=>$BTN['pay_link'],'url'=>$res['url']]]]];
api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode($kb,JSON_UNESCAPED_UNICODE)]);
api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['paylink_ready']]);
return;
}
if($data==='m_card'){
if(($st['phase']??'')!=='method'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
if(function_exists('admin_flags_is_disabled')&&admin_flags_is_disabled('card')){api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['method_disabled']]);return;}
$total=(int)($st['total']??get_total($st));
$card=(defined('ADMIN_CARD')&&ADMIN_CARD)?ADMIN_CARD:((defined('CARD_NUMBER')&&CARD_NUMBER)?CARD_NUMBER:'6219-0000-0000-0000');
    $currency=$TXT['currency_suffix_plain']??'';
    $amount_tpl=$TXT['card_amount_value_template']??'';
    $amount_line=$amount_tpl!==''?strtr($amount_tpl,['{amount}'=>number_format($total),'{currency}'=>$currency]):number_format($total).($currency!==''?' '.$currency:'');
$text=$TXT['card_number_label'].'<code>'.$card.'</code>'."\n".$TXT['card_amount_label'].$amount_line."\n".$TXT['card_after_label'];
$kb=['inline_keyboard'=>[[['text'=>$BTN['card_paid'],'callback_data'=>'card_paid']],[['text'=>$BTN['change_method'],'callback_data'=>'back_method']]]];
api('editMessageText',['chat_id'=>$cid,'message_id'=>$mid,'text'=>$text,'parse_mode'=>'HTML','disable_web_page_preview'=>true]);
api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode($kb,JSON_UNESCAPED_UNICODE)]);
$st['phase']='card_info_shown';
$st['total']=$total;
save_state($cid,$st);
api('answerCallbackQuery',['callback_query_id'=>$qid]);
return;
}
if($data==='back_method'){
if(!in_array(($st['phase']??''),['pay_auto','card_info_shown'])){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
$st['phase']='method';
save_state($cid,$st);
api('editMessageText',['chat_id'=>$cid,'message_id'=>$mid,'text'=>$TXT['method_title'],'parse_mode'=>'HTML']);
api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode(method_kb(),JSON_UNESCAPED_UNICODE)]);
api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['back_to_method']]);
return;
}
if($data==='card_paid'){
if(!in_array(($st['phase']??''),['card_info_shown','await_receipt','await_admin_confirm'])){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
    $user_link_tpl=$TXT['user_link_template']??'';
    $generic_user=$TXT['user_generic_label']??'';
    $mention=$un?('@'.$un):($user_link_tpl!==''?strtr($user_link_tpl,['{user_id}'=>$uid,'{label}'=>$generic_user]):$generic_user);
api('sendMessage',['chat_id'=>$cid,'text'=>$mention.' '.$TXT['card_send_receipt_prompt'],'parse_mode'=>'HTML']);
$st['phase']='await_receipt';
save_state($cid,$st);
api('answerCallbackQuery',['callback_query_id'=>$qid]);
return;
}
if(strpos($data,'admin_ok:')===0){
if(($st['phase']??'')!=='await_admin_confirm'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
if(!admin_is_user($uid)){api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['only_admin_btn']]);return;}
$rid=substr($data,9);
if(!isset($st['receipts'][$rid])){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
$winner_uid=(int)$st['receipts'][$rid]['from'];
$st['buyer_id']=$winner_uid;
    $user_link_tpl=$TXT['user_link_template']??'';
$buyer_username=$st['buyer_username']??'';
    $buyer_label=$buyer_username!==''?'@'.$buyer_username:($TXT['buyer_label']??'');
    $buyer_tag=$user_link_tpl!==''?strtr($user_link_tpl,['{user_id}'=>$winner_uid,'{label}'=>$buyer_label]):$buyer_label;
$seller_id=(int)($st['seller_id']??0);
    $unknown_label=$TXT['unknown_user_label']??'';
    $seller_tag=$unknown_label;
if($seller_id>0){
$seller_username=$st['seller_username']??'';
    $seller_label=$seller_username!==''?'@'.$seller_username:($TXT['seller_label']??'');
    $seller_tag=$user_link_tpl!==''?strtr($user_link_tpl,['{user_id}'=>$seller_id,'{label}'=>$seller_label]):$seller_label;
}
$buyer_token=bin2hex(random_bytes(8));
$seller_token=bin2hex(random_bytes(8));
$st['link_tokens']=['buyer'=>$buyer_token,'seller'=>$seller_token];
$st['link_tokens_used']=['buyer'=>null,'seller'=>null];
if(isset($st['receipts'])&&is_array($st['receipts'])){
foreach($st['receipts'] as $r=>$info){
$rmid=(int)($info['msg_id']??0);
if($rmid>0){api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$rmid,'reply_markup'=>json_encode(['inline_keyboard'=>[]],JSON_UNESCAPED_UNICODE)]);}
}
}
$st['phase']='done';
save_state($cid,$st);
$tpl=$TXT['admin_paid_msg'];
$botu=$TXT['bot_username'];
$msg=strtr($tpl,['{seller_tag}'=>$seller_tag,'{buyer_tag}'=>$buyer_tag,'{bot_username}'=>$botu,'{buyer_token}'=>$buyer_token,'{seller_token}'=>$seller_token]);
api('sendMessage',['chat_id'=>$cid,'text'=>$msg,'parse_mode'=>'HTML','disable_web_page_preview'=>true]);
api('answerCallbackQuery',['callback_query_id'=>$qid]);
return;
}
api('answerCallbackQuery',['callback_query_id'=>$qid]);
}
