<?php
function handle_update($u){
global $TXT,$BTN;
if(isset($u['callback_query'])){handle_cb($u['callback_query']);return;}
if(isset($u['message'])){handle_msg($u['message']);return;}
}
function is_valid_act_pass($p){
if(preg_match('/[\x{0600}-\x{06FF}]/u',$p))return false;
if(preg_match('/\s/',$p))return false;
return (bool)preg_match('/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z0-9!@#$%^&*()\-\_=+\[\]{};:,.?<>\/\\\\|~`]{4,64}$/',$p);
}
function ensure_admin_group_link($gid,&$st){
    if(isset($st['group_username'])&&$st['group_username']!==''){
        return 'https://t.me/'.$st['group_username'];
    }
    $cached=trim((string)($st['admin_group_link']??''));
    if($cached!==''){
        return $cached;
    }
    $res=api('exportChatInviteLink',['chat_id'=>$gid]);
    if(isset($res['ok'])&&$res['ok']&&isset($res['result'])&&is_string($res['result'])&&$res['result']!==''){
        $st['admin_group_link']=$res['result'];
        save_state($gid,$st);
        return $st['admin_group_link'];
    }
    return '';
}

function start_plan_now($cid,$chat,$uid_hint){
global $TXT,$BTN;
$st=load_state($cid);
if($st&&($st['phase']??'')!=='done'){return;}
$st=[
    'phase'=>'rules',
    'kyc'=>[],
    'acks'=>[],
    'kyc_on'=>false,
    'misc_on'=>false,
    'acc_check_on'=>true,
    'fb_change'=>null,
    'fee_acc_check'=>5000,
    'token'=>bin2hex(random_bytes(4)),
    'link_tokens'=>null,
    'link_tokens_used'=>['buyer'=>null,'seller'=>null],
    'group_username'=>($chat['username']??'')
];
save_state($cid,$st);
api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['rules_title'],'parse_mode'=>'HTML','reply_markup'=>json_encode(rules_kb($st,$uid_hint,false),JSON_UNESCAPED_UNICODE)]);
}
function autoplan_on_join($cid,$chat,$members){
$apf=data_dir().'/ap_'.$cid.'.json';
$rec=@json_decode(@file_get_contents($apf),true);
if(!is_array($rec)){$rec=['first'=>0,'users'=>[],'scheduled'=>false];}
$now=time();
$first=(int)($rec['first']??0);
$users=$rec['users']??[];
if(!is_array($users)){$users=[];}
if($first<=0||($now-$first)>1800){
$rec=['first'=>$now,'users'=>[],'scheduled'=>false];
$users=[];
$first=$now;
}
if(is_array($members)){
foreach($members as $m){
$uid=(int)($m['id']??0);
if($uid<=0)continue;
if(!in_array($uid,$users,true)){$users[]=$uid;}
}
}
$rec['users']=$users;
$ok=count($users)>=2;
if($ok&&!($rec['scheduled']??false)){
$rec['scheduled']=true;
@file_put_contents($apf,json_encode($rec,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX);
$st=load_state($cid);
if(!$st||($st['phase']??'')==='done'){sleep(10);start_plan_now($cid,$chat,0);}
@unlink($apf);
}else{
@file_put_contents($apf,json_encode($rec,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX);
}
}
function user_bridge_forward($uid,$txt){
global $TXT;
$trim=trim($txt);
if($trim===''){return false;}
$lower=mb_strtolower($trim,'UTF-8');
$files=list_plan_files();
foreach($files as $f){
$a=@json_decode(@file_get_contents($f),true);
if(!is_array($a))continue;
$br=$a['bridge']??null;
if(!is_array($br)||!($br['on']??false))continue;
$admin_id=(int)($br['admin']??0);
if($admin_id<=0)continue;
$side=$br['side']??'';
$gid=(int)($br['gid']??0);
    if($side==='buyer'&&(string)$uid===(string)($a['buyer_id']??'')){
if($lower==='done'){
$a['bridge']['on']=false;
save_state($gid,$a);
api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['bridge_finished_user'],'parse_mode'=>'HTML']);
api('sendMessage',['chat_id'=>$admin_id,'text'=>$TXT['bridge_finished'],'parse_mode'=>'HTML']);
return true;
}
api('sendMessage',['chat_id'=>$admin_id,'text'=>$TXT['reply_from_buyer_prefix'].$txt,'parse_mode'=>'HTML']);
api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['bridge_forwarded'],'parse_mode'=>'HTML']);
return true;
}
    if($side==='seller'&&(string)$uid===(string)($a['seller_id']??'')){
if($lower==='done'){
$a['bridge']['on']=false;
save_state($gid,$a);
api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['bridge_finished_user'],'parse_mode'=>'HTML']);
api('sendMessage',['chat_id'=>$admin_id,'text'=>$TXT['bridge_finished'],'parse_mode'=>'HTML']);
return true;
}
api('sendMessage',['chat_id'=>$admin_id,'text'=>$TXT['reply_from_seller_prefix'].$txt,'parse_mode'=>'HTML']);
api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['bridge_forwarded'],'parse_mode'=>'HTML']);
return true;
}
}
return false;
}

function send_price_prompt($chat_id,$text,$target_uid=null,$trigger_message=null,$reply_to_message_id=null){
    $reply_markup=['force_reply'=>true];
    if($target_uid!==null&&$target_uid!==0){
        $reply_markup['selective']=true;
        $mention='<a href="tg://user?id='.(int)$target_uid.'">&#8205;</a>';
        if(strpos($text,'tg://user?id='.(int)$target_uid)===false){
            $text=$mention.$text;
        }
    }
    $reply_to=null;
    if($reply_to_message_id!==null){
        $reply_to=(int)$reply_to_message_id;
    }elseif(is_array($trigger_message)){
        if(isset($trigger_message['message_id'])){
            $reply_to=(int)$trigger_message['message_id'];
        }elseif(isset($trigger_message['reply_to_message'])&&is_array($trigger_message['reply_to_message'])&&isset($trigger_message['reply_to_message']['message_id'])){
            $reply_to=(int)$trigger_message['reply_to_message']['message_id'];
        }
    }
    if($reply_to&&$reply_to<=0){
        $reply_to=null;
    }
    $params=[
        'chat_id'=>$chat_id,
        'text'=>$text,
        'parse_mode'=>'HTML',
        'reply_markup'=>json_encode($reply_markup,JSON_UNESCAPED_UNICODE)
    ];
    if($reply_to){
        $params['reply_to_message_id']=$reply_to;
    }
    return api('sendMessage',$params);
}

function resolve_plan_user_context($uid,$st,$chat_id,$ux_override=null){
    $result=[
        'role'=>null,
        'need'=>null,
        'stale'=>false,
        'context'=>null,
    ];
    $ux=$ux_override;
    if($ux===null){$ux=load_uctx($uid);}    
    if(!$ux){return $result;}
    $result['context']=$ux;
    if((string)($ux['chat_id']??'')!==(string)$chat_id){return $result;}
    $ux_role=$ux['role']??'';
    $result['need']=$ux['need']??null;
    $ux_token=(string)($ux['token']??'');
    $current_token=(string)($st['token']??'');
    if($ux_token!==''&&$current_token!==''){
        if(hash_equals($ux_token,$current_token)){
            // ok
        }else{
            $ux_role='';
            $result['stale']=true;
        }
    }else{
        if($ux_role==='buyer'&&(string)($st['buyer_id']??'')!==(string)$uid){$ux_role='';}
        if($ux_role==='seller'&&(string)($st['seller_id']??'')!==(string)$uid){$ux_role='';}
    }
    if($ux_role==='buyer'||$ux_role==='seller'){
        $result['role']=$ux_role;
    }
    return $result;
}

function refresh_admin_paid_message($chat_id,$st){
    global $TXT;
    $mid=(int)($st['admin_paid_msg_id']??0);
    if($mid<=0){
        return;
    }
    $tpl=$TXT['admin_paid_msg']??'';
    if($tpl===''){
        return;
    }
    $link_tokens=$st['link_tokens']??null;
    if(!is_array($link_tokens)){
        return;
    }
    $buyer_token=$link_tokens['buyer']??'';
    $seller_token=$link_tokens['seller']??'';
    if($buyer_token===''||$seller_token===''){
        return;
    }
    $user_link_tpl=$TXT['user_link_template']??'';
    $unknown_label=$TXT['unknown_user_label']??'';
    $buyer_tag=$unknown_label;
    $buyer_id=(int)($st['buyer_id']??0);
    if($buyer_id>0){
        $buyer_username=$st['buyer_username']??'';
        $buyer_label=$buyer_username!==''?'@'.$buyer_username:($TXT['buyer_label']??'');
        if($buyer_label===''){
            $buyer_label=$unknown_label;
        }
        $buyer_tag=$user_link_tpl!==''
            ? strtr($user_link_tpl,['{user_id}'=>$buyer_id,'{label}'=>$buyer_label])
            : $buyer_label;
    }
    $seller_tag=$unknown_label;
    $seller_id=(int)($st['seller_id']??0);
    if($seller_id>0){
        $seller_username=$st['seller_username']??'';
        $seller_label=$seller_username!==''?'@'.$seller_username:($TXT['seller_label']??'');
        if($seller_label===''){
            $seller_label=$unknown_label;
        }
        $seller_tag=$user_link_tpl!==''
            ? strtr($user_link_tpl,['{user_id}'=>$seller_id,'{label}'=>$seller_label])
            : $seller_label;
    }
    $botu=$TXT['bot_username']??'';
    $msg=strtr(
        $tpl,
        [
            '{seller_tag}'=>$seller_tag,
            '{buyer_tag}'=>$buyer_tag,
            '{bot_username}'=>$botu,
            '{buyer_token}'=>$buyer_token,
            '{seller_token}'=>$seller_token,
        ]
    );
    api(
        'editMessageText',
        [
            'chat_id'=>$chat_id,
            'message_id'=>$mid,
            'text'=>$msg,
            'parse_mode'=>'HTML',
            'disable_web_page_preview'=>true,
        ]
    );
}

function handle_msg($m){
global $TXT,$BTN;
$from=$m['from']??[];
$uid=$from['id']??0;
$un=$from['username']??'';
$chat=$m['chat']??[];
$cid=$chat['id']??0;
$ctype=$chat['type']??'';
$txt=trim($m['text']??'');
if(in_array($ctype,['group','supergroup'])&&isset($m['new_chat_members'])&&is_array($m['new_chat_members'])){autoplan_on_join($cid,$chat,$m['new_chat_members']);}
if($ctype==='private'&&function_exists('channel_enforce_join')){
$ctx=['chat_type'=>'private','message_id'=>$m['message_id']??0,'force_on_error'=>true];
if(!channel_enforce_join($uid,$cid,$ctx))return;
}
$cmd='';
if($txt&&$txt[0]=='/'){if(preg_match('/^\/([A-Za-z_]+)(?:@[\w_]+)?/u',$txt,$mm)){$cmd=strtolower($mm[1]);}}
if($ctype==='private'&&admin_is_user($uid)){
    if(function_exists('admin_card_editor_handle_message')&&admin_card_editor_handle_message($uid,$m)){
        return;
    }
}
if(in_array($ctype,['group','supergroup'])&&isset($m['new_chat_members'])&&is_array($m['new_chat_members'])){autoplan_on_join($cid,$chat,$m['new_chat_members']);}
if(in_array($ctype,['group','supergroup'])&&$cmd!==''&&function_exists('channel_enforce_join')){
$ctx=['chat_type'=>$ctype,'message_id'=>$m['message_id']??0,'command'=>$cmd,'reply_to'=>$m['message_id']??0];
if(!channel_enforce_join($uid,$cid,$ctx))return;
}
if(in_array($ctype,['group','supergroup'])&&$cmd==='plan'){
$st=load_state($cid);
if($st&&($st['phase']??'')!=='done'){api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['plan_busy'],'parse_mode'=>'HTML']);return;}
start_plan_now($cid,$chat,$uid);
return;
}
if(in_array($ctype,['group','supergroup'])&&$cmd==='clean'){
$lim_ok=true;
$is_admin=admin_is_user($uid);
if(!$is_admin){
$lf=data_dir().'/limit.json';
$all=@json_decode(@file_get_contents($lf),true);if(!is_array($all))$all=[];
$key=(string)$cid;
$w=$all[$key]??['ts'=>[]];
$now=time();
$w['ts']=array_values(array_filter($w['ts'],function($t)use($now){return ($now-$t)<=1800;}));
if(count($w['ts'])>=2){$lim_ok=false;api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['clean_limit'],'parse_mode'=>'HTML']);}else{$w['ts'][]=$now;$all[$key]=$w;@file_put_contents($lf,json_encode($all,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX);}
}
if(!$lim_ok)return;
del_state($cid);
api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['clean_ok'],'parse_mode'=>'HTML']);
if(!$is_admin){sleep(3);start_plan_now($cid,$chat,$uid);}
return;
}
if($ctype==='group'||$ctype==='supergroup'){
$st=load_state($cid);
    if($st&&($st['phase']??'')==='await_receipt'&&((isset($m['photo'])&&is_array($m['photo']))||isset($m['document']))){
    $amt=(int)($st['total']??get_total($st));
    $admin_tag=admin_mentions_text($TXT);
    $msg=($admin_tag!==''?$admin_tag.' ':'').$TXT['receipt_agreed_amount_prefix'].number_format($amt).$TXT['receipt_agreed_amount_suffix']."\n".$TXT['admin_wait_confirm_short'];
$rid=bin2hex(random_bytes(3));
$kb=['inline_keyboard'=>[[['text'=>$BTN['admin_approve'],'callback_data'=>'admin_ok:'.$rid]]]];
$res=api('sendMessage',['chat_id'=>$cid,'text'=>$msg,'parse_mode'=>'HTML','reply_to_message_id'=>$m['message_id'],'allow_sending_without_reply'=>true,'reply_markup'=>json_encode($kb,JSON_UNESCAPED_UNICODE)]);
if(!isset($st['receipts'])||!is_array($st['receipts'])){$st['receipts']=[];}
$st['receipts'][$rid]=['from'=>$uid,'msg_id'=>$res['result']['message_id']??0];
$st['phase']='await_admin_confirm';
save_state($cid,$st);
return;
}
    if($st&&($st['phase']??'')==='await_seller_log'){
        $seller_id=(int)($st['seller_id']??0);
        if($seller_id>0&&$uid===$seller_id){
            $has_media=false;
            if(isset($m['photo'])&&is_array($m['photo'])){$has_media=true;}
            if(isset($m['video'])){$has_media=true;}
            if(isset($m['document'])){$has_media=true;}
            if($has_media){
                $buyer_id=(int)($st['buyer_id']??0);
                $user_link_tpl=$TXT['user_link_template']??'';
                $missing_html=$TXT['admin_info_missing_value']??'<b>نامشخص</b>';
                $buyer_tag=$missing_html;
                if($buyer_id>0){
                    $buyer_username=$st['buyer_username']??'';
                    $buyer_label=$buyer_username!==''?'@'.$buyer_username:($TXT['buyer_label']??'');
                    $buyer_tag=$user_link_tpl!==''?strtr($user_link_tpl,['{user_id}'=>$buyer_id,'{label}'=>$buyer_label]):$buyer_label;
                }
                $prompt_tpl=$TXT['log_buyer_prompt']??'';
                $prompt_text=$prompt_tpl!==''?strtr($prompt_tpl,['{buyer}'=>$buyer_tag]):$buyer_tag;
                $kb=['inline_keyboard'=>[[['text'=>$BTN['log_confirm_btn']??'✔️ تایید','callback_data'=>'log_confirm:'.$cid]]]];
                $params=[
                    'chat_id'=>$cid,
                    'text'=>$prompt_text,
                    'parse_mode'=>'HTML',
                    'reply_to_message_id'=>$m['message_id']??null,
                    'allow_sending_without_reply'=>true,
                    'reply_markup'=>json_encode($kb,JSON_UNESCAPED_UNICODE)
                ];
                $res=api('sendMessage',$params);
                $st['phase']='await_buyer_confirm';
                $st['await_log']=[
                    'seller_id'=>$seller_id,
                    'buyer_id'=>$buyer_id,
                    'seller_message_id'=>$m['message_id']??0,
                    'prompt_message_id'=>$res['result']['message_id']??0
                ];
                save_state($cid,$st);
                return;
            }
        }
    }
    }
    if($txt&&strpos($txt,'/start')===0&&$ctype==='private'){
        preg_match('/^\/start\s*(.*)$/',$txt,$mm);
        $param=trim($mm[1]??'');
        $info=parse_start($param);
        if(!$info){
            api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['greet'],'parse_mode'=>'HTML']);
            return;
        }
        if(($info['kind']??'')==='get'){
            $found=find_chat_by_token($info['token']);
            if(!$found){
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['invalid_link'],'parse_mode'=>'HTML']);
                return;
            }
            $role=$found['role'];
            $chat_id=$found['chat_id'];
            $st=load_state($chat_id);
            if(!$st){
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['invalid_link'],'parse_mode'=>'HTML']);
                return;
            }
            $known_role='';
            if((string)($st['buyer_id']??'')===(string)$uid){$known_role='buyer';}
            if((string)($st['seller_id']??'')===(string)$uid){$known_role='seller';}
            $ctx=resolve_plan_user_context($uid,$st,$chat_id);
            if($ctx['role']!==null){$known_role=$ctx['role'];}
            $expected_id=$role==='buyer'?(int)($st['buyer_id']??0):(int)($st['seller_id']??0);
            if($expected_id>0&&$expected_id!==$uid){
                $deny_key=$role==='buyer'?'link_not_allowed_for_buyer':'link_not_allowed_for_seller';
                $deny_txt=$TXT[$deny_key]??($TXT['invalid_link']??'');
                api('sendMessage',['chat_id'=>$uid,'text'=>$deny_txt,'parse_mode'=>'HTML']);
                return;
            }
            if($known_role==='buyer'&&$role==='seller'){
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['link_wrong_for_buyer'],'parse_mode'=>'HTML']);
                return;
            }
            if($known_role==='seller'&&$role==='buyer'){
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['link_wrong_for_seller'],'parse_mode'=>'HTML']);
                return;
            }
            if(!isset($st['link_tokens_used'])||!is_array($st['link_tokens_used'])){
                $st['link_tokens_used']=['buyer'=>null,'seller'=>null];
            }
            $used_b=$st['link_tokens_used']['buyer'];
            $used_s=$st['link_tokens_used']['seller'];
            if(($role==='buyer'&&$used_b!==null&&$used_b!=$uid)||($role==='seller'&&$used_s!==null&&$used_s!=$uid)){
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['link_used_by_other'],'parse_mode'=>'HTML']);
                return;
            }
            if(($role==='buyer'&&$used_s!==null&&$used_s==$uid)||($role==='seller'&&$used_b!==null&&$used_b==$uid)){
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['link_cannot_use_both'],'parse_mode'=>'HTML']);
                return;
            }
            if($role==='buyer'){
                if(is_whitelisted_user($uid)){
                    api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['whitelisted_user_rejected']??'<b>دسترسی مجاز نیست</b>','parse_mode'=>'HTML']);
                    return;
                }
                $st['link_tokens_used']['buyer']=$uid;
                $st['buyer_id']=$uid;
                $st['buyer_username']=$un??'';
                save_state($chat_id,$st);
                refresh_admin_paid_message($chat_id,$st);
                save_uctx($uid,['chat_id'=>$chat_id,'role'=>'buyer','token'=>$st['token']??'']);
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['buyer_start'],'parse_mode'=>'HTML']);
                return;
            }
            if(is_whitelisted_user($uid)){
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['whitelisted_user_rejected']??'<b>دسترسی مجاز نیست</b>','parse_mode'=>'HTML']);
                return;
            }
            $st['link_tokens_used']['seller']=$uid;
            $st['seller_id']=$uid;
            $st['seller_username']=$un??'';
            save_state($chat_id,$st);
            refresh_admin_paid_message($chat_id,$st);
            save_uctx($uid,['chat_id'=>$chat_id,'role'=>'seller','need'=>'email','token'=>$st['token']??'']);
            api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['seller_start'],'parse_mode'=>'HTML']);
            return;
        }
        if(($info['kind']??'')==='role'){
            $st=load_state($info['chat_id']);
            if(!$st||($st['token']??'')!==$info['token']){
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['invalid_link'],'parse_mode'=>'HTML']);
                return;
            }
            $known_role='';
            if((string)($st['buyer_id']??'')===(string)$uid){$known_role='buyer';}
            if((string)($st['seller_id']??'')===(string)$uid){$known_role='seller';}
            $ctx=resolve_plan_user_context($uid,$st,$info['chat_id']);
            if($ctx['role']!==null){$known_role=$ctx['role'];}
            $expected_id=$info['role']==='buyer'?(int)($st['buyer_id']??0):(int)($st['seller_id']??0);
            if($expected_id>0&&$expected_id!==$uid){
                $deny_key=$info['role']==='buyer'?'link_not_allowed_for_buyer':'link_not_allowed_for_seller';
                $deny_txt=$TXT[$deny_key]??($TXT['invalid_link']??'');
                api('sendMessage',['chat_id'=>$uid,'text'=>$deny_txt,'parse_mode'=>'HTML']);
                return;
            }
            if($known_role==='buyer'&&$info['role']==='seller'){
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['link_wrong_for_buyer'],'parse_mode'=>'HTML']);
                return;
            }
            if($known_role==='seller'&&$info['role']==='buyer'){
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['link_wrong_for_seller'],'parse_mode'=>'HTML']);
                return;
            }
            if($info['role']==='buyer'){
                if(is_whitelisted_user($uid)){
                    api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['whitelisted_user_rejected']??'<b>دسترسی مجاز نیست</b>','parse_mode'=>'HTML']);
                    return;
                }
                if(($st['buyer_id']??0)===0){
                    $st['buyer_id']=$uid;
                    $st['buyer_username']=$un??'';
                }elseif($st['buyer_id']!=$uid){
                    api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['buyer_already'],'parse_mode'=>'HTML']);
                    return;
                }
                save_state($info['chat_id'],$st);
                refresh_admin_paid_message($info['chat_id'],$st);
                save_uctx($uid,['chat_id'=>$info['chat_id'],'role'=>'buyer','token'=>$st['token']??'']);
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['buyer_start'],'parse_mode'=>'HTML']);
                return;
            }
            if(is_whitelisted_user($uid)){
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['whitelisted_user_rejected']??'<b>دسترسی مجاز نیست</b>','parse_mode'=>'HTML']);
                return;
            }
            if(($st['seller_id']??0)===0){
                $st['seller_id']=$uid;
                $st['seller_username']=$un??'';
            }elseif($st['seller_id']!=$uid){
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['seller_already'],'parse_mode'=>'HTML']);
                return;
            }
            save_state($info['chat_id'],$st);
            refresh_admin_paid_message($info['chat_id'],$st);
            save_uctx($uid,['chat_id'=>$info['chat_id'],'role'=>'seller','need'=>'email','token'=>$st['token']??'']);
            api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['seller_start'],'parse_mode'=>'HTML']);
            return;
        }
        api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['invalid_link'],'parse_mode'=>'HTML']);
        return;
    }
    if($ctype==='private'&&admin_is_user($uid)&&$txt!==''){
        if(admin_on_private_text($uid,$txt))return;
    }
    if($ctype==='private'&&$txt){
        $ux=load_uctx($uid);
        if($ux){
            $gid=$ux['chat_id'];
            $st=load_state($gid);
            if(!$st){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['plan_not_found'],'parse_mode'=>'HTML']);return;}
            $ctx=resolve_plan_user_context($uid,$st,$gid,$ux);
            if($ctx['stale']){
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['invalid_link'],'parse_mode'=>'HTML']);
                return;
            }
            $ux_role=$ctx['role']??'';
            if($ux_role==='buyer'){
                if(!preg_match('/^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$/',$txt)){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['send_valid_email_buyer'],'parse_mode'=>'HTML']);return;}
                $st['buyer_email']=$txt;
                save_state($gid,$st);
                api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['buyer_email_ok'],'parse_mode'=>'HTML']);
                return;
            }
            if($ux_role==='seller'){
                $await_code=$st['await_code']??false;
                if($await_code){
                    $code_admin_id=0;
                    if(is_array($await_code)){
                        $code_admin_id=(int)($await_code['admin']??0);
                    }
                    $group_label=$TXT['seller_code_group_label']??'Group:';
                    $code_tpl=$TXT['seller_code_template']??'';
                    $glink=ensure_admin_group_link($gid,$st);
                    $user_link_tpl=$TXT['user_link_template']??'';
                    $view_profile=$TXT['admin_profile_view_label']??'';
                    $missing_html=$TXT['admin_info_missing_value']??'<b>نامشخص</b>';
                    $seller_id=(int)($st['seller_id']??0);
                    $seller_username=$st['seller_username']??'';
                    $seller_link_label=$seller_username!==''?'@'.$seller_username:$view_profile;
                    $seller_tag=$seller_id>0
                        ? ($user_link_tpl!==''?strtr($user_link_tpl,['{user_id}'=>$seller_id,'{label}'=>$seller_link_label]):$seller_link_label)
                        : $missing_html;
                    $buyer_id=(int)($st['buyer_id']??0);
                    $buyer_username=$st['buyer_username']??'';
                    $buyer_link_label=$buyer_username!==''?'@'.$buyer_username:$view_profile;
                    $buyer_tag=$buyer_id>0
                        ? ($user_link_tpl!==''?strtr($user_link_tpl,['{user_id}'=>$buyer_id,'{label}'=>$buyer_link_label]):$buyer_link_label)
                        : $missing_html;
                    $buyer_email_txt=trim((string)($st['buyer_email']??''));
                    $buyer_email_html=$buyer_email_txt!==''?'<code>'.htmlspecialchars($buyer_email_txt).'</code>':$missing_html;
                    if(($st['seller_pass']??'')===''){
                        $st['seller_pass']=generate_trade_password();
                        save_state($gid,$st);
                    }
                    $seller_pass_txt=$st['seller_pass']??'';
                    $seller_pass_html=$seller_pass_txt!==''?'<code>'.htmlspecialchars($seller_pass_txt).'</code>':$missing_html;
                    $send=strtr($code_tpl,[
                        '{code}'=>htmlspecialchars($txt),
                        '{group_id}'=>$gid,
                        '{group_label}'=>$group_label,
                        '{seller}'=>$seller_tag,
                        '{buyer}'=>$buyer_tag,
                        '{buyer_email}'=>$buyer_email_html,
                        '{seller_pass}'=>$seller_pass_html,
                    ]);
                    $code_kb=[
                        [
                            ['text'=>$BTN['seller_code_btn_finish']??'تکمیل چنج ✔️','callback_data'=>'finish_change:'.$gid]
                        ],
                        [
                            ['text'=>$BTN['seller_code_btn_expired']??'کد چنج منقضی فروشنده','callback_data'=>'seller_code_expired:'.$gid]
                        ],
                        [
                            ['text'=>$BTN['seller_code_btn_email_wrong']??'جیمیل غلط خریدار','callback_data'=>'buyer_email_wrong:'.$gid]
                        ],
                        [
                            $glink!==''
                                ? ['text'=>$BTN['seller_code_btn_group']??'لینک گروه','url'=>$glink]
                                : ['text'=>$BTN['seller_code_btn_group']??'لینک گروه','callback_data'=>'no_group:'.$gid]
                        ]
                    ];
                    $reply_markup=json_encode(['inline_keyboard'=>$code_kb],JSON_UNESCAPED_UNICODE);
                    $admin_info_msgs=[];
                    if(is_array($st['admin_info_msgs']??null)){
                        $admin_info_msgs=$st['admin_info_msgs'];
                    }
                    $delivered=false;
                    if($code_admin_id>0){
                        $params=[
                            'chat_id'=>$code_admin_id,
                            'text'=>$send,
                            'parse_mode'=>'HTML',
                            'disable_web_page_preview'=>true,
                            'reply_markup'=>$reply_markup
                        ];
                        $reply_key=(string)$code_admin_id;
                        if(isset($admin_info_msgs[$reply_key])&&(int)$admin_info_msgs[$reply_key]>0){
                            $params['reply_to_message_id']=(int)$admin_info_msgs[$reply_key];
                            $params['allow_sending_without_reply']=true;
                        }
                        $res=api('sendMessage',$params);
                        $delivered=(isset($res['ok'])&&$res['ok']);
                    }
                    if(!$delivered){
                        $admin_ids=admin_all_ids();
                        foreach($admin_ids as $aid){
                            $aid=(int)$aid;
                            if($aid<=0){
                                continue;
                            }
                            if($code_admin_id>0&&$aid===$code_admin_id){
                                continue;
                            }
                            $params=[
                                'chat_id'=>$aid,
                                'text'=>$send,
                                'parse_mode'=>'HTML',
                                'disable_web_page_preview'=>true,
                                'reply_markup'=>$reply_markup
                            ];
                            $reply_key=(string)$aid;
                            if(isset($admin_info_msgs[$reply_key])&&(int)$admin_info_msgs[$reply_key]>0){
                                $params['reply_to_message_id']=(int)$admin_info_msgs[$reply_key];
                                $params['allow_sending_without_reply']=true;
                            }
                            $res=api('sendMessage',$params);
                            if(isset($res['ok'])&&$res['ok']){
                                $delivered=true;
                            }
                        }
                    }
                    if(!$delivered){
                        api('sendMessage',['chat_id'=>$uid,'text'=>$send,'parse_mode'=>'HTML']);
                    }
                    $st['await_code']=false;
                    save_state($gid,$st);
                    api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['code_sent_to_admin'],'parse_mode'=>'HTML']);
                    return;
                }
                $need=$ctx['need']??'email';
                if($need==='email'){
                    if(!preg_match('/^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$/',$txt)){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['send_valid_email_seller'],'parse_mode'=>'HTML']);return;}
                    $st['seller_email']=$txt;
                    save_state($gid,$st);
                    save_uctx($uid,['chat_id'=>$gid,'role'=>'seller','need'=>'pass','token'=>$st['token']??'']);
                    api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['ask_pass'],'parse_mode'=>'HTML']);
                    return;
                }
                if($need==='pass'){
                    if(!is_valid_act_pass($txt)){api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['pass_invalid'],'parse_mode'=>'HTML']);return;}
                    $st['seller_input_pass']=$txt;
                    $st['seller_pass']=generate_trade_password();
                    save_state($gid,$st);
                    save_uctx($uid,['chat_id'=>$gid,'role'=>'seller','need'=>'done','token'=>$st['token']??'']);
                    api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['seller_info_ok'],'parse_mode'=>'HTML']);
                    if(empty($st['notified_admin'])){
                        $st['notified_admin']=true;
                        $glink=ensure_admin_group_link($gid,$st);
                        $user_link_tpl=$TXT['user_link_template']??'';
                        $view_profile=$TXT['admin_profile_view_label']??'';
                        $missing_html=$TXT['admin_info_missing_value']??'<b>نامشخص</b>';
                        $missing_plain=trim(strip_tags($missing_html));
                        $seller_id=(int)($st['seller_id']??0);
                        $seller_username=$st['seller_username']??'';
                        $seller_link_label=$seller_username!==''?'@'.$seller_username:$view_profile;
                        $seller_tag=$seller_id>0
                            ? ($user_link_tpl!==''?strtr($user_link_tpl,['{user_id}'=>$seller_id,'{label}'=>$seller_link_label]):$seller_link_label)
                            : $missing_html;
                        $buyer_id=(int)($st['buyer_id']??0);
                        $buyer_username=$st['buyer_username']??'';
                        $buyer_link_label=$buyer_username!==''?'@'.$buyer_username:$view_profile;
                        $buyer_tag=$buyer_id>0
                            ? ($user_link_tpl!==''?strtr($user_link_tpl,['{user_id}'=>$buyer_id,'{label}'=>$buyer_link_label]):$buyer_link_label)
                            : $missing_html;
                        $seller_email_txt=trim($st['seller_email']??'');
                        $seller_email_plain=$seller_email_txt!==''?htmlspecialchars($seller_email_txt):$missing_plain;
                        $seller_email_html=$seller_email_txt!==''?'<b>'.htmlspecialchars($seller_email_txt).'</b>':$missing_html;
                        if(($st['seller_pass']??'')===''){
                            $st['seller_pass']=generate_trade_password();
                            save_state($gid,$st);
                        }
                        $seller_pass_txt=$st['seller_pass']??'';
                        $seller_pass_plain=$seller_pass_txt!==''?htmlspecialchars($seller_pass_txt):$missing_plain;
                        $seller_pass_html=$seller_pass_txt!==''?'<b>'.htmlspecialchars($seller_pass_txt).'</b>':$missing_html;
                        $buyer_email_txt=trim($st['buyer_email']??'');
                        $buyer_email_plain=$buyer_email_txt!==''?htmlspecialchars($buyer_email_txt):$missing_plain;
                        $buyer_email_html=$buyer_email_txt!==''?'<b>'.htmlspecialchars($buyer_email_txt).'</b>':$missing_html;
                        $info_tpl=$TXT['admin_info_template']??'';
                        if($info_tpl!==''){
                            $adm_text=strtr($info_tpl,[
                                '{buyer}'=>$buyer_tag,
                                '{buyer_email}'=>$buyer_email_plain,
                                '{seller}'=>$seller_tag,
                                '{seller_email}'=>$seller_email_plain,
                                '{seller_pass}'=>$seller_pass_plain,
                            ]);
                        }else{
                            $adm_text=$TXT['admin_info_title']."\n"
                                .$TXT['admin_info_buyer'].$buyer_tag."\n"
                                .$TXT['admin_info_buyer_email']."\n".$buyer_email_html."\n"
                                .$TXT['admin_info_seller'].$seller_tag."\n"
                                .$TXT['admin_info_email']."\n".$seller_email_html."\n"
                                .$TXT['admin_info_pass']."\n".$seller_pass_html;
                        }
                        $kb_rows=[
                            [
                                ['text'=>$BTN['admin_request_code'],'callback_data'=>'req_code:'.$gid]
                            ],
                            [
                                ['text'=>$BTN['admin_msg_seller'],'callback_data'=>'msg_seller:'.$gid],
                                ['text'=>$BTN['admin_msg_buyer'],'callback_data'=>'msg_buyer:'.$gid]
                            ],
                            [
                                ['text'=>$BTN['seller_wrong'],'callback_data'=>'seller_bad:'.$gid]
                            ],
                            [
                                $glink!==''
                                    ? ['text'=>$BTN['admin_group'],'url'=>$glink]
                                    : ['text'=>$BTN['admin_group'],'callback_data'=>'no_group:'.$gid]
                            ]
                        ];
                        $kb=['inline_keyboard'=>$kb_rows];
                        $admin_info_msgs=[];
                        if(is_array($st['admin_info_msgs']??null)){
                            $admin_info_msgs=$st['admin_info_msgs'];
                        }
                        $admin_ids=admin_all_ids();
                        $sent_any=false;
                        foreach($admin_ids as $aid){
                            $aid=(int)$aid;
                            if($aid<=0){
                                continue;
                            }
                            $params=[
                                'chat_id'=>$aid,
                                'text'=>$adm_text,
                                'parse_mode'=>'HTML',
                                'disable_web_page_preview'=>true,
                                'reply_markup'=>json_encode($kb,JSON_UNESCAPED_UNICODE)
                            ];
                            $res=api('sendMessage',$params);
                            if(isset($res['ok'])&&$res['ok']){
                                $sent_any=true;
                                if(isset($res['result']['message_id'])){
                                    $admin_info_msgs[(string)$aid]=(int)$res['result']['message_id'];
                                }
                            }
                        }
                        if(!$sent_any){
                            api('sendMessage',[
                                'chat_id'=>$uid,
                                'text'=>$adm_text,
                                'parse_mode'=>'HTML',
                                'disable_web_page_preview'=>true,
                                'reply_markup'=>json_encode($kb,JSON_UNESCAPED_UNICODE)
                            ]);
                        }else{
                            $st['admin_info_msgs']=$admin_info_msgs;
                        }
                        save_state($gid,$st);
                    }
                    return;
                }
            }
            api('sendMessage',['chat_id'=>$uid,'text'=>$TXT['invalid_link'],'parse_mode'=>'HTML']);
            return;
        }
}
        if($ctype==='private'&&$txt!==''){
            if(user_bridge_forward($uid,$txt)){
                return;
            }
        }
        if(in_array($ctype,['group','supergroup'])&&$txt&&!$cmd){
            $st=load_state($cid);
            if($st&&($st['phase']??'')==='await_price'){
                if(!preg_match('/^\d[\d, ]*$/',$txt)){
                    send_price_prompt($cid,$TXT['only_number_price'],$uid,$m,$m['message_id']??null);
                    return;
                }
                $amount=(int)str_replace([',',' '],['',''],$txt);
                if($amount<50000){
                    send_price_prompt($cid,$TXT['min_price'],$uid,$m,$m['message_id']??null);
                    return;
                }
                $base=compute_fee($amount);
                $extra=((isset($st['fb_change'])&&$st['fb_change']===true)?10000:0);
                $misc=((bool)($st['misc_on']??false))?10000:0;
                $kycfee=((bool)($st['kyc_on']??false))?5000:0;
                $acc_check_fee=((bool)($st['acc_check_on']??true))?5000:0;
                $st['amount']=$amount;
                $st['fee_base']=$base;
                $st['fee_extra_change']=$extra;
                $st['fee_misc']=$misc;
                $st['kyc_fee']=$kycfee;
                $st['fee_acc_check']=$acc_check_fee;
                $st['fee']=$base+$extra+$misc;
                $st['total']=$amount+$base+$extra+$misc+$kycfee+$acc_check_fee;
                $st['phase']='invoice';
                $st['amt_acks']=[];
                save_state($cid,$st);
                $msg=api('sendMessage',[
                    'chat_id'=>$cid,
                    'text'=>invoice_text($st),
                    'parse_mode'=>'HTML',
                    'reply_markup'=>json_encode(invoice_kb($st,$uid,false),JSON_UNESCAPED_UNICODE),
                ]);
                api('pinChatMessage',[
                    'chat_id'=>$cid,
                    'message_id'=>$msg['result']['message_id']??null,
                    'disable_notification'=>true,
                ]);
                return;
            }
        }
    }

function handle_cb($cb){
global $TXT,$BTN;
$qid=$cb['id']??'';
$from=$cb['from']??[];
$uid=$from['id']??0;
$un=$from['username']??'';
$msg=$cb['message']??[];
$chat=$msg['chat']??[];
$cid=$chat['id']??0;
$mid=$msg['message_id']??0;
$data=$cb['data']??'';
if(($chat['type']??'')==='private'){
if(function_exists('channel_handle_callback')&&channel_handle_callback($cb))return;
if(function_exists('channel_enforce_join')){
$ctx=['chat_type'=>'private','message_id'=>$mid,'force_on_error'=>true];
if(!channel_enforce_join($uid,$cid,$ctx)){
if($qid!==''){api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>defined('CHANNEL_FORCE_JOIN_ALERT_TEXT')?CHANNEL_FORCE_JOIN_ALERT_TEXT:'برای استفاده از ربات ابتدا عضو کانال شوید','show_alert'=>true]);}
return;
}
}
}
if(!$cid){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
$st=load_state($cid);
$thread_id=(int)($msg['message_thread_id']??0);
if($st){
    if($thread_id>0&&((int)($st['topic_id']??0)!==$thread_id)){
        $st['topic_id']=$thread_id;
        save_state($cid,$st);
    }
}
if($thread_id>0&&strpos($data,'finish_change:')===0){
    $target_gid=(int)substr($data,14);
    if($target_gid>0&&$target_gid===$cid&&(!$st||((int)($st['topic_id']??0)!==$thread_id))){
        $target_state=$st?:load_state($target_gid);
        if($target_state&&((int)($target_state['topic_id']??0)!==$thread_id)){
            $target_state['topic_id']=$thread_id;
            save_state($target_gid,$target_state);
            if($target_gid===$cid){
                $st=$target_state;
            }
        }
    }
}
if(admin_on_callback($data,$uid,$qid,$cid,$mid,$st))return;
if(!$st){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
if(in_array($data,['tgl_act','tgl_fb','tgl_gg','tgl_kyc','tgl_misc','tgl_acc_check','ack_go','lock'])){
if(($st['phase']??'')!=='rules'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
if($data==='lock'){api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['lock_btn']]);return;}
if($data==='tgl_kyc'){$st['kyc_on']=!((bool)($st['kyc_on']??false));save_state($cid,$st);}
if($data==='tgl_misc'){$st['misc_on']=!((bool)($st['misc_on']??false));if(($st['misc_on']??false)===true){$st['kyc']=[];}$st['fb_change']=null;save_state($cid,$st);}
if($data==='tgl_acc_check'){$st['acc_check_on']=!((bool)($st['acc_check_on']??true));$st['fee_acc_check']=($st['acc_check_on']??false)?5000:0;save_state($cid,$st);}
if(in_array($data,['tgl_act','tgl_fb','tgl_gg'])){
if(($st['misc_on']??false)===true){api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['need_method']]);return;}
$map=['tgl_act'=>'act','tgl_fb'=>'fb','tgl_gg'=>'gg'];
$k=$map[$data];
$arr=$st['kyc']??[];
if(in_array($k,$arr)){$arr=array_values(array_diff($arr,[$k]));}else{$arr[]=$k;}
$st['kyc']=$arr;
save_state($cid,$st);
}
if($data==='ack_go'){
if(!isset($st['acks'])){$st['acks']=[];}
$st['acks'][$uid]=true;
save_state($cid,$st);
}
$need_both=(bool)($st['kyc_on']??false);
$ack_count=count($st['acks']??[]);
$acks_ok=$need_both?($ack_count>=2):($ack_count>=1);
$has_method=(($st['misc_on']??false)===true)||(count($st['kyc']??[])>=1);
        if($acks_ok&&$has_method){
            $ask_fb=(($st['misc_on']??false)!==true)&&need_fb_question($st)&&($st['fb_change']===null);
            api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode(rules_kb($st,$uid,true),JSON_UNESCAPED_UNICODE)]);
            if($ask_fb){
                $st['phase']='fb_change';
                save_state($cid,$st);
                api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['rules_need_fbq'],'parse_mode'=>'HTML','reply_markup'=>json_encode(fbq_kb(false),JSON_UNESCAPED_UNICODE)]);
                api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['req_price_ack']]);
                return;
            }else{
                $st['phase']='await_price';
                save_state($cid,$st);
                send_price_prompt($cid,$TXT['await_price'],$uid,$msg,$msg['message_id']??null);
                $msgtxt=$need_both?$TXT['both_then_next']:$TXT['ack_done'];
                api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$msgtxt]);
                return;
            }
        }else{
$hint=(!$has_method)?$TXT['need_method']:($need_both?(($ack_count==1)?$TXT['wait_second_user']:$TXT['need_both']):$TXT['need_one']);
api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode(rules_kb($st,$uid,false),JSON_UNESCAPED_UNICODE)]);
api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$hint]);
return;
}
}
if(in_array($data,['fbchg_on','fbchg_off'])){
if(($st['phase']??'')!=='fb_change'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
        $st['fb_change']=($data==='fbchg_on');
        save_state($cid,$st);
        api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode(fbq_kb(true),JSON_UNESCAPED_UNICODE)]);
        $st['phase']='await_price';
        save_state($cid,$st);
        send_price_prompt($cid,$TXT['await_price'],$uid,$msg,$msg['message_id']??null);
        api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['ack_done']]);
        return;
    }
    if(in_array($data,['amt_ok','amt_edit'])){
        if(($st['phase']??'')!=='invoice'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
        if($data==='amt_edit'){
            $st['phase']='await_price';
            $st['amt_acks']=[];
            save_state($cid,$st);
            send_price_prompt($cid,$TXT['edit_price'],$uid,$msg,$msg['message_id']??null);
            api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['edited_price_ack']]);
            return;
        }
if($data==='amt_ok'){
if(!isset($st['amt_acks'])){$st['amt_acks']=[];}
$st['amt_acks'][$uid]=true;
save_state($cid,$st);
api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode(['inline_keyboard'=>[]],JSON_UNESCAPED_UNICODE)]);
$st['phase']='method';
save_state($cid,$st);
api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['method_title'],'parse_mode'=>'HTML','reply_markup'=>json_encode(method_kb(),JSON_UNESCAPED_UNICODE)]);
api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['ack_done']]);
return;
}
}
if($data==='m_auto'){
if(($st['phase']??'')!=='method'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
if(function_exists('admin_flags_is_disabled')&&admin_flags_is_disabled('auto')){api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['method_disabled']]);return;}
$total=(int)($st['total']??get_total($st));
$st['phase']='pay_auto';
$st['total']=$total;
$st['payer_id']=null;
save_state($cid,$st);
$kb=['inline_keyboard'=>[[['text'=>$BTN['build_pay'],'callback_data'=>'build_pay']],[['text'=>$BTN['change_method'],'callback_data'=>'back_method']]]];
    $total_prefix=$TXT['invoice_total_value_prefix']??'';
    $total_suffix=$TXT['invoice_total_value_suffix']??'';
    $total_line=$total_prefix.number_format($total).$total_suffix;
    api('editMessageText',['chat_id'=>$cid,'message_id'=>$mid,'text'=>$TXT['invoice_total_title']."\n".$total_line,'parse_mode'=>'HTML']);
api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode($kb,JSON_UNESCAPED_UNICODE)]);
api('answerCallbackQuery',['callback_query_id'=>$qid]);
return;
}
if($data==='build_pay'){
if(($st['phase']??'')!=='pay_auto'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
$st['payer_id']=$uid;
save_state($cid,$st);
$res=build_zp_link($cid,$st['total'],$uid);
if(!$res['ok']){$err=$res['err']??($TXT['build_pay_error']??'');api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$err]);return;}
$kb=['inline_keyboard'=>[[['text'=>$BTN['pay_link'],'url'=>$res['url']]]]];
api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode($kb,JSON_UNESCAPED_UNICODE)]);
api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['paylink_ready']]);
return;
}
if($data==='m_card'){
if(($st['phase']??'')!=='method'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
if(function_exists('admin_flags_is_disabled')&&admin_flags_is_disabled('card')){api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['method_disabled']]);return;}
$total=(int)($st['total']??get_total($st));
$types=card_types_all();
if(empty($types)){
    $text=card_build_payment_text('', '', $total);
    $kb=['inline_keyboard'=>[[['text'=>$BTN['card_paid'],'callback_data'=>'card_paid']],[['text'=>$BTN['change_method'],'callback_data'=>'back_method']]]];
    api('editMessageText',['chat_id'=>$cid,'message_id'=>$mid,'text'=>$text,'parse_mode'=>'HTML','disable_web_page_preview'=>true]);
    api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode($kb,JSON_UNESCAPED_UNICODE)]);
    $st['phase']='card_info_shown';
    $st['total']=$total;
    save_state($cid,$st);
    api('answerCallbackQuery',['callback_query_id'=>$qid]);
    return;
}
$prompt=$TXT['card_select_title']??'';
if($prompt===''){$prompt='<b>نوع کارت مورد نظر را انتخاب کنید</b>';}
$amount_info=card_build_payment_text('', '', $total);
if($amount_info!==''){
    $prompt=$amount_info;
}
$rows=[];
$fallback_label=$TXT['card_type_fallback_label']??'کارت';
$buttons=[];
foreach($types as $type){
    $label=$type['title']!==''?$type['title']:$fallback_label;
    $buttons[]=['text'=>$label,'callback_data'=>'card_type:'.$type['id']];
}
$chunk=[];
foreach($buttons as $btn){
    $chunk[]=$btn;
    if(count($chunk)>=3){
        $rows[]=$chunk;
        $chunk=[];
    }
}
if(!empty($chunk)){
    $rows[]=$chunk;
}
$rows[]=[['text'=>$BTN['change_method'],'callback_data'=>'back_method']];
api('editMessageText',['chat_id'=>$cid,'message_id'=>$mid,'text'=>$prompt,'parse_mode'=>'HTML','disable_web_page_preview'=>true]);
api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode(['inline_keyboard'=>$rows],JSON_UNESCAPED_UNICODE)]);
$st['phase']='card_select';
$st['total']=$total;
save_state($cid,$st);
api('answerCallbackQuery',['callback_query_id'=>$qid]);
return;
}
if(strpos($data,'card_type:')===0){
    if(($st['phase']??'')!=='card_select'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
    $type_id=trim(substr($data,10));
    $type=$type_id!==''?card_type_get($type_id):null;
    if(!$type){
        api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['card_select_missing']??'']);
        return;
    }
    $total=(int)($st['total']??get_total($st));
    $text=card_build_payment_text($type['card_number'],$type['holder'],$total);
    $kb_paid_only=['inline_keyboard'=>[[['text'=>$BTN['card_paid'],'callback_data'=>'card_paid']]]];
    $kb_with_change=$kb_paid_only;
    $kb_with_change['inline_keyboard'][]=[['text'=>$BTN['change_method'],'callback_data'=>'back_method']];
    $sticker_mid=null;
    $sticker_sent=false;
    $text_mid=null;
    $sticker=trim($type['sticker']??'');

    $msg_params=['chat_id'=>$cid,'text'=>$text,'parse_mode'=>'HTML','disable_web_page_preview'=>true];
    $include_kb_on_text=($sticker==='');
    if($include_kb_on_text){
        $msg_params['reply_markup']=json_encode($kb_with_change,JSON_UNESCAPED_UNICODE);
    }
    $text_res=api('sendMessage',$msg_params);
    if(isset($text_res['ok'])&&$text_res['ok']){
        $text_mid=$text_res['result']['message_id']??null;
    }

    if($sticker!==''){
        $sticker_params=['chat_id'=>$cid,'sticker'=>$sticker,'reply_markup'=>json_encode($kb_with_change,JSON_UNESCAPED_UNICODE)];
        if($text_mid){
            $sticker_params['reply_to_message_id']=$text_mid;
            $sticker_params['allow_sending_without_reply']=true;
        }
        $res=api('sendSticker',$sticker_params);
        if(isset($res['ok'])&&$res['ok']){
            $sticker_mid=$res['result']['message_id']??null;
            $sticker_sent=true;
        }
    }

    if(!$sticker_sent&&!$include_kb_on_text){
        if($text_mid){
            api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$text_mid,'reply_markup'=>json_encode($kb_with_change,JSON_UNESCAPED_UNICODE)]);
        }else{
            api('sendMessage',['chat_id'=>$cid,'text'=>$text,'parse_mode'=>'HTML','disable_web_page_preview'=>true,'reply_markup'=>json_encode($kb_with_change,JSON_UNESCAPED_UNICODE)]);
        }
    }
    api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode(['inline_keyboard'=>[]],JSON_UNESCAPED_UNICODE)]);
    $st['phase']='card_info_shown';
    $st['total']=$total;
    $st['card_selected_type']=$type['id'];
    save_state($cid,$st);
    $notice_tpl=$TXT['card_selected_notice']??'';
    $notice=$notice_tpl!==''?strtr($notice_tpl,['{title}'=>$type['title']!==''?$type['title']:($TXT['card_type_fallback_label']??'')]):'';
    if($notice!==''){
        api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$notice]);
    }else{
        api('answerCallbackQuery',['callback_query_id'=>$qid]);
    }
    return;
}
if($data==='back_method'){
if(!in_array(($st['phase']??''),['pay_auto','card_info_shown','card_select'])){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
$st['phase']='method';
save_state($cid,$st);
    $reply_markup=json_encode(method_kb(),JSON_UNESCAPED_UNICODE);
    if(isset($msg['text'])&&$msg['text']!==''){
        api('editMessageText',['chat_id'=>$cid,'message_id'=>$mid,'text'=>$TXT['method_title'],'parse_mode'=>'HTML']);
        api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>$reply_markup]);
    }elseif(isset($msg['caption'])){
        api('editMessageCaption',['chat_id'=>$cid,'message_id'=>$mid,'caption'=>$TXT['method_title'],'parse_mode'=>'HTML']);
        api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>$reply_markup]);
    }else{
        api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$mid,'reply_markup'=>json_encode(['inline_keyboard'=>[]],JSON_UNESCAPED_UNICODE)]);
        api('sendMessage',['chat_id'=>$cid,'text'=>$TXT['method_title'],'parse_mode'=>'HTML','reply_markup'=>$reply_markup]);
    }
api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['back_to_method']]);
return;
}
if($data==='card_paid'){
if(!in_array(($st['phase']??''),['card_info_shown','await_receipt','await_admin_confirm'])){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
    $user_link_tpl=$TXT['user_link_template']??'';
    $generic_user=$TXT['user_generic_label']??'';
    $mention=$un?('@'.$un):($user_link_tpl!==''?strtr($user_link_tpl,['{user_id}'=>$uid,'{label}'=>$generic_user]):$generic_user);
api('sendMessage',['chat_id'=>$cid,'text'=>$mention.' '.$TXT['card_send_receipt_prompt'],'parse_mode'=>'HTML']);
$st['phase']='await_receipt';
save_state($cid,$st);
api('answerCallbackQuery',['callback_query_id'=>$qid]);
return;
}
if(strpos($data,'admin_ok:')===0){
if(($st['phase']??'')!=='await_admin_confirm'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
if(!admin_is_user($uid)){api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$TXT['only_admin_btn']]);return;}
$rid=substr($data,9);
if(!isset($st['receipts'][$rid])){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
$winner_uid=(int)$st['receipts'][$rid]['from'];
$buyer_id=0;
if($winner_uid>0){
    if(is_whitelisted_user($winner_uid)){
        if((int)($st['buyer_id']??0)===$winner_uid){
            $st['buyer_id']=0;
            if(isset($st['buyer_username'])){$st['buyer_username']='';}
        }
    }else{
        $st['buyer_id']=$winner_uid;
        if(isset($st['buyer_username'])&&$st['buyer_username']!==''){$st['buyer_username']='';}
        $buyer_id=$winner_uid;
    }
}
auto_assign_trade_roles($st);
$buyer_id=(int)($st['buyer_id']??0);
    $user_link_tpl=$TXT['user_link_template']??'';
    $unknown_label=$TXT['unknown_user_label']??'';
    $buyer_tag=$unknown_label;
if($buyer_id>0){
$buyer_username=$st['buyer_username']??'';
    $buyer_label=$buyer_username!==''?'@'.$buyer_username:($TXT['buyer_label']??'');
    $buyer_tag=$user_link_tpl!==''?strtr($user_link_tpl,['{user_id}'=>$buyer_id,'{label}'=>$buyer_label]):$buyer_label;
}
$seller_id=(int)($st['seller_id']??0);
    $seller_tag=$unknown_label;
if($seller_id>0){
$seller_username=$st['seller_username']??'';
    $seller_label=$seller_username!==''?'@'.$seller_username:($TXT['seller_label']??'');
    $seller_tag=$user_link_tpl!==''?strtr($user_link_tpl,['{user_id}'=>$seller_id,'{label}'=>$seller_label]):$seller_label;
}
$buyer_token=bin2hex(random_bytes(8));
$seller_token=bin2hex(random_bytes(8));
$tpl=$TXT['admin_paid_msg'];
$botu=$TXT['bot_username'];
$msg=strtr($tpl,['{seller_tag}'=>$seller_tag,'{buyer_tag}'=>$buyer_tag,'{bot_username}'=>$botu,'{buyer_token}'=>$buyer_token,'{seller_token}'=>$seller_token]);
$threading_params=admin_build_threading_params($st);
$msg_params=$threading_params;
$msg_params['chat_id']=$cid;
$msg_params['text']=$msg;
$msg_params['parse_mode']='HTML';
$msg_params['disable_web_page_preview']=true;
$res=admin_send_group_message_with_thread_guard($cid,$msg_params,$st);
$admin_paid_msg_id=0;
if(!isset($res['ok'])||!$res['ok']){
    $alert=$TXT['admin_paid_send_error']??'';
    if($alert===''){$alert='Error';}
    $desc=trim((string)($res['description']??''));
    if($desc!==''){$alert.="\n".$desc;}
    api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$alert,'show_alert'=>true]);
    return;
}
$st['phase']='done';
$st['link_tokens']=['buyer'=>$buyer_token,'seller'=>$seller_token];
$st['link_tokens_used']=['buyer'=>null,'seller'=>null];
if(isset($st['receipts'])&&is_array($st['receipts'])){
foreach($st['receipts'] as $r=>$info){
$rmid=(int)($info['msg_id']??0);
if($rmid>0){api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$rmid,'reply_markup'=>json_encode(['inline_keyboard'=>[]],JSON_UNESCAPED_UNICODE)]);}
}
}
$admin_paid_msg_id=0;
$admin_paid_msg_id=(int)($res['result']['message_id']??0);
$topic_id=(int)($st['topic_id']??0);
$sent_thread_id=(int)($res['result']['message_thread_id']??0);
if($sent_thread_id>0&&$sent_thread_id!==$topic_id){
    $topic_id=$sent_thread_id;
    $st['topic_id']=$topic_id;
}
$st['admin_paid_msg_id']=$admin_paid_msg_id;
save_state($cid,$st);
api('answerCallbackQuery',['callback_query_id'=>$qid]);
return;
}
if(strpos($data,'log_confirm:')===0){
    if(($st['phase']??'')!=='await_buyer_confirm'){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
    $target_gid=(int)substr($data,12);
    if($target_gid!==0&&$target_gid!=$cid){api('answerCallbackQuery',['callback_query_id'=>$qid]);return;}
    $buyer_id=(int)($st['buyer_id']??0);
    if($buyer_id<=0||$uid!==$buyer_id){
        $warn=$TXT['log_only_buyer']??'';
        if($warn!==''){
            api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$warn,'show_alert'=>true]);
        }else{
            api('answerCallbackQuery',['callback_query_id'=>$qid]);
        }
        return;
    }
    $await_log=is_array($st['await_log']??null)?$st['await_log']:[];
    $prompt_mid=(int)($await_log['prompt_message_id']??0);
    if($prompt_mid>0){
        api('editMessageReplyMarkup',['chat_id'=>$cid,'message_id'=>$prompt_mid,'reply_markup'=>json_encode(['inline_keyboard'=>[]],JSON_UNESCAPED_UNICODE)]);
    }
    $seller_id=(int)($st['seller_id']??0);
    $user_link_tpl=$TXT['user_link_template']??'';
    $missing_html=$TXT['admin_info_missing_value']??'<b>نامشخص</b>';
    $seller_tag=$missing_html;
    if($seller_id>0){
        $seller_username=$st['seller_username']??'';
        $seller_label=$seller_username!==''?'@'.$seller_username:($TXT['seller_label']??'');
        $seller_tag=$user_link_tpl!==''?strtr($user_link_tpl,['{user_id}'=>$seller_id,'{label}'=>$seller_label]):$seller_label;
    }
    $admin_tag=admin_mentions_text($TXT);
    $lines=[];
    $confirm_tpl=$TXT['log_confirmed_group_message']??'';
    if($confirm_tpl!==''){
        $final_text=strtr($confirm_tpl,['{seller}'=>$seller_tag,'{admins}'=>$admin_tag]);
    }else{
        $seller_line_tpl=$TXT['log_confirmed_seller_line']??'';
        if($seller_line_tpl!==''){
            $lines[]=strtr($seller_line_tpl,['{seller}'=>$seller_tag]);
        }elseif($seller_tag!==''){
            $lines[]='• '.$seller_tag.' → «شماره کارت را ارسال کنید.»';
        }
        $admin_line_tpl=$TXT['log_confirmed_admin_line']??'';
        if($admin_line_tpl!==''){
            $lines[]=strtr($admin_line_tpl,['{admins}'=>$admin_tag]);
        }elseif($admin_tag!==''){
            $lines[]='• '.$admin_tag.' → «مراحل چنج تایید شد؛ جهت واریز یا ادامه معامله اقدام کنید.»';
        }
        $final_text=trim(implode("\n",array_filter($lines)));
    }
    if($final_text!==''){
        api('sendMessage',['chat_id'=>$cid,'text'=>$final_text,'parse_mode'=>'HTML','disable_web_page_preview'=>true]);
    }
    $st['phase']='post_change';
    $st['await_log']=null;
    save_state($cid,$st);
    $ack=$TXT['log_confirm_ack']??($TXT['sent']??'');
    if($ack!==''){
        api('answerCallbackQuery',['callback_query_id'=>$qid,'text'=>$ack]);
    }else{
        api('answerCallbackQuery',['callback_query_id'=>$qid]);
    }
    return;
}
api('answerCallbackQuery',['callback_query_id'=>$qid]);
}
