<?php
require __DIR__.'/config.php';
require __DIR__.'/txt.php';
require __DIR__.'/helpers.php';
$pid=isset($_GET['chat_id'])?trim($_GET['chat_id']):'';
$amount_rial=isset($_GET['amount'])?intval($_GET['amount']):0;
$merchant=(defined('ZP_MERCHANT_ID')?ZP_MERCHANT_ID:(defined('MerchantID')?MerchantID:''));if($merchant===''){$merchant=(isset($MerchantID)?$MerchantID:'');}
if($pid===''||$amount_rial<=0||$merchant===''){http_response_code(400);$title=$TXT['zp_req_bad_request_title']??'';$msg=$TXT['zp_req_bad_request_message']??'';echo '<!DOCTYPE html><meta charset="utf-8"><title>'.$title.'</title><div style="font-family:sans-serif;direction:rtl;padding:20px">'.$msg.'</div>';exit;}
function zp_find_plan_by_payer(string $uid):?int{$files=list_plan_files();$best=null;$bestTime=0;foreach($files as $f){$a=@json_decode(@file_get_contents($f),true);if(!is_array($a))continue;if((string)($a['payer_id']??'')===(string)$uid){$mtime=@filemtime($f);if($mtime>$bestTime){$bestTime=$mtime;$best=(int)str_replace(['plan_','.json'],['',''],basename($f));}}}return $best;}
$gid=zp_find_plan_by_payer($pid);if(!$gid){http_response_code(404);$title=$TXT['zp_req_not_found_title']??'';$msg=$TXT['zp_req_not_found_message']??'';echo '<!DOCTYPE html><meta charset="utf-8"><title>'.$title.'</title><div style="font-family:sans-serif;direction:rtl;padding:20px">'.$msg.'</div>';exit;}
$st=load_state($gid);if(!$st){http_response_code(404);$title=$TXT['zp_req_not_found_title']??'';$msg=$TXT['zp_req_missing_data_message']??'';echo '<!DOCTYPE html><meta charset="utf-8"><title>'.$title.'</title><div style="font-family:sans-serif;direction:rtl;padding:20px">'.$msg.'</div>';exit;}
if((int)($st['total']??get_total($st))<=0){http_response_code(400);$title=$TXT['zp_req_total_zero_title']??'';$msg=$TXT['zp_req_total_zero_message']??'';echo '<!DOCTYPE html><meta charset="utf-8"><title>'.$title.'</title><div style="font-family:sans-serif;direction:rtl;padding:20px">'.$msg.'</div>';exit;}
if(isset($st['zp']['status'])&&$st['zp']['status']==='done'){$title=$TXT['zp_req_expired_title']??'';$msg=$TXT['zp_req_expired_message']??'';echo '<!DOCTYPE html><meta charset="utf-8"><title>'.$title.'</title><div style="font-family:sans-serif;direction:rtl;padding:20px">'.$msg.'</div>';exit;}
$scheme=((isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http');$host=$_SERVER['HTTP_HOST']??'';$base=rtrim((defined('BASE_URL')&&BASE_URL!=='')?BASE_URL:($scheme.'://'.$host),'/');
$callback=$base.'/zp_back.php?chat_id='.rawurlencode($pid).'&amount='.$amount_rial;
$desc_tpl=$TXT['zp_req_description_template']??'';
$payload=['merchant_id'=>$merchant,'amount'=>$amount_rial,'callback_url'=>$callback,'description'=>$desc_tpl!==''?strtr($desc_tpl,['{group_id}'=>$gid]):'', 'metadata'=>['order_id'=>(string)$gid,'payer_id'=>$pid]];
$j=json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
$ch=curl_init('https://api.zarinpal.com/pg/v4/payment/request.json');
curl_setopt_array($ch,[CURLOPT_USERAGENT=>'ZarinPal Rest Api v4',CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$j,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Content-Type: application/json','Content-Length: '.strlen($j)],CURLOPT_FOLLOWLOCATION=>true,CURLOPT_CONNECTTIMEOUT=>15,CURLOPT_TIMEOUT=>25]);
$res=curl_exec($ch);
$err=curl_error($ch);
curl_close($ch);
$logfile=__DIR__.'/infopay.json';
$log=function($row)use($logfile){$fp=@fopen($logfile,'c+');if($fp){@flock($fp,LOCK_EX);$old=@stream_get_contents($fp);$log=@json_decode($old,true);if(!is_array($log))$log=[];$log[]=$row;rewind($fp);ftruncate($fp,0);fwrite($fp,json_encode($log,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT));fflush($fp);@flock($fp,LOCK_UN);fclose($fp);}};
if($err){$log(['type'=>'request_error','time'=>date('c'),'payer_id'=>$pid,'group_id'=>$gid,'amount_rial'=>$amount_rial,'amount_toman'=>intval($amount_rial/10),'error'=>$err,'ip'=>($_SERVER['REMOTE_ADDR']??''),'ua'=>($_SERVER['HTTP_USER_AGENT']??'')]);http_response_code(502);$title=$TXT['zp_req_error_title']??'';$msg=$TXT['zp_req_gateway_error_message']??'';echo '<!DOCTYPE html><meta charset="utf-8"><title>'.$title.'</title><div style="font-family:sans-serif;direction:rtl;padding:20px">'.$msg.'</div>';exit;}
$a=@json_decode($res,true);
if(is_array($a)&&empty($a['errors'])&&isset($a['data']['code'],$a['data']['authority'])&&intval($a['data']['code'])===100){$auth=$a['data']['authority'];$st['zp']=['authority'=>$auth,'amount_rial'=>$amount_rial,'created_at'=>date('c'),'status'=>'pending','payer_id'=>$pid];$st['phase']='pay_auto';save_state($gid,$st);$log(['type'=>'request','time'=>date('c'),'payer_id'=>$pid,'group_id'=>$gid,'amount_rial'=>$amount_rial,'amount_toman'=>intval($amount_rial/10),'authority'=>$auth,'ip'=>($_SERVER['REMOTE_ADDR']??''),'ua'=>($_SERVER['HTTP_USER_AGENT']??'')]);$payUrl='https://www.zarinpal.com/pg/StartPay/'.$auth;$redir_title=$TXT['zp_req_redirect_title']??'';$redir_heading=$TXT['zp_req_redirect_heading']??'';$redir_hint=$TXT['zp_req_redirect_hint']??'';$redir_button=$TXT['zp_req_redirect_button']??'';echo '<!DOCTYPE html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>'.$redir_title.'</title><meta http-equiv="refresh" content="0;url='.$payUrl.'"><style>body{margin:0;font-family:sans-serif;background:#0e1116;color:#e8eef5;display:flex;align-items:center;justify-content:center;min-height:100vh}._card{max-width:520px;width:100%;background:#141a23;border:1px solid #223043;border-radius:14px;padding:20px;box-shadow:0 20px 60px rgba(0,0,0,.35)}._btn{display:inline-block;padding:12px 18px;background:#00d68f;color:#0b1220;border-radius:10px;font-weight:800;text-decoration:none}</style></head><body><div class="_card"><div style="margin-bottom:12px;font-weight:800">'.$redir_heading.'</div><div style="font-size:13px;color:#a8b3c2;margin-bottom:16px">'.$redir_hint.'</div><a class="_btn" href="'.$payUrl.'" rel="noopener" target="_blank">'.$redir_button.'</a></div><script>setTimeout(function(){if(document.visibilityState!=="hidden"){location.replace("'.$payUrl.'");}},300);</script></body></html>';exit;}
$log(['type'=>'request_fail','time'=>date('c'),'payer_id'=>$pid,'group_id'=>$gid,'amount_rial'=>$amount_rial,'amount_toman'=>intval($amount_rial/10),'zp_errors'=>($a['errors']??[]),'ip'=>($_SERVER['REMOTE_ADDR']??''),'ua'=>($_SERVER['HTTP_USER_AGENT']??'')]);
http_response_code(500);
$title=$TXT['zp_req_error_title']??'';
$msg=$TXT['zp_req_create_error_message']??'';
echo '<!DOCTYPE html><meta charset="utf-8"><title>'.$title.'</title><div style="font-family:sans-serif;direction:rtl;padding:20px">'.$msg.'</div>';
